### PR TITLE
Api Clean Architecture setup

### PR DESCRIPTION
**Pull request by MisterQuack**
Set up clean architecture for a dotnet 8 REST API. Includes the following layers and their base:
- src/Watson.**Core**
- src/Watson.**Application**
- src/Watson.**Web**
- src/Watson.**Adapter.SqlServer**
- tests/UnitTests
- tests/IntegrationTests

clean-architecture

--- 

This pull request unfortunately (and by choice) does not contain any features that make use of the mediator pattern as of yet. So therefore we have a small description on how features can be added

Controllers can extend the `BaseApiController` class, this will allow Controllers to make use of the `Mediator` attribute. A controller should do nothing more than pass Commands to the Mediator.

The Application layer will contain all logic. Each Feature can get their own folder inside the `Feature` folder. Let's say that we have a Todo app. We will implement our Todo features inside the folder `Features/Todo/Commands` and `Features/Todo/Queries`. We make use of the CQRS separation.

A create command for this supposed feature can live inside the `CreateTodo.cs` file. This file will contain the **IRequest** implementation, **IRequestHandler** implementation, a return view model if relevant and `AbstractValidator` implementation if validation is needed. Below is an example of how this could look.

_Application/Features/Todo/Commands/CreateTodo.cs_
```cs
    public class CreateTodoCommand : IRequest<Response<Guid>>
    {
        public string Title { get; set; }
        public string DetailedDescription { get; set; }
    }

    public class CreateTodoCommandHandler : IRequestHandler<CreateTodoCommand, Response<Guid>>
    {
        private readonly ITodoRepository _todoRepository;
        private readonly IMapper _mapper;

        public CreateAreaCommandHandler(ITodoRepository todoRepository, IMapper mapper)
        {
            _todoRepository = todoRepository;
            _mapper = mapper;
        }

        public async Task<Response<Guid>> Handle(CreateTodoCommand request, CancellationToken cancellationToken)
        {
            var todo = _mapper.Map<Todo>(request);

            await _todoRepository.AddAsync(todo);
            return new Response<Guid>(todo.Id);
        }
    }

    public class CreateTodoCommandValidator : AbstractValidator<CreateTodoCommand>
    {
        public CreateTodoCommandValidator()
        {
            RuleFor(t => t.Name)
                .NotEmpty().WithMessage("{PropertyName} is required")
                .NotNull()
                .MaximumLength(20).WithMessage("{PropertyName} must not exceed 20 characters");
        }
    }
```

I think that the repository pattern and automapper portions are self explanatory. Each repository can extend the GenericRepository to implement basic features like CRUD and Pagination. Automapper mappings can be added in `GeneralProfile.cs` or another file that's alike.

---

The Appsettings.Development.json file includes a connectionstring that refers to a local database with some fake credentials, meant to be used in development only. The `README.md` includes the command to spin up this database on the right port with the right settings using Docker. 

Migrations will run automatically. Creating Migrations will go as usual, but make sure that you select the correct project (namely the **Persistence project**).

### CODE REVIEW

**Comment by Romano999** [comment]
Persistence? I see why we would need a database, but we should discuss which we are going to use. In my opinion the namespace should look something like Adapter.{Database}/Persistence.{Database} or in your case like Watson.Infrastructure.Persistence.{Database} (which is quite a long name).

**Comment by MisterQuack** [comment]
> Persistence? I see why we would need a database, but we should discuss which we are going to use. In my opinion the namespace should look something like Adapter.{Database}/Persistence.{Database} or in your case like Watson.Infrastructure.Persistence.{Database} (which is quite a long name).

Yeah very good that you mentioned it, I just used SQL Server because we generally use that one. I think using a Database like Postgres or even something light would be more suitable for this project. We can discuss this offline when you're available.

I don't mind a rename to either one below for the persistence layer:
- `Watson.Infrastructure.Persistence.<DatabaseName>`
- `Watson.Infrastructure.Database.<DatabaseName>`
- `Watson.Infrastructure.Data.<DatabaseName>` (This one has my preference so far for a shorter name)

**Comment by Romano999** [comment]
Couldn't we strip either Infrastructure or Persistence? IMO we should just go for Adapter.SqlServer.

hexagonal

We could go for the approach higlighted in the image above. In this approach we would define the "Port" interfaces in our Core project, which our Adapter projects would implement.

See this as reference https://herbertograca.com/2017/09/14/ports-adapters-architecture/

**Comment by MisterQuack** [comment]
Yeah an _Adapter_ is the same as an_Infrastructure_. An infrastructure is however not always an Adapter. Infrastructure refers to a **Upstream** Adapter. We can rename it to either `Watson.Adapter.SqlServer` or `Watson.Infrastructure.SqlServer` if that's what you mean?

Should we also discuss using a different database? Or will we do this at a later moment?

**Comment by Romano999** [comment]
Yeah, making it `Watson.Adapter.SqlServer` would make it clear we are adhering to the Ports and Adapter pattern. As for the database, SqlServer should be fine for now.

**Comment by MisterQuack** [comment]
Alright, will rename it in a minute

**Review by Romano999 — APPROVED** [review]

**Pull request merged**
